server:
  port: 9005
  servlet:
    context-path: /

spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://172.17.0.4:3306/spring_boot_db?useSSL=false&serverTimezone=UTC&characterEncoding=utf-8
    username: root
    password: LxR52013141220

  redis:
    host: 192.168.203.128
    port: 6379

  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8

mybatis:
  # 配置类型别名包扫描
  type-aliases-package: com.djh.springjdbc.entity
  # sql语句映射文件路径
  mapper-locations:
    - classpath:mapper/*.xml
  # 驼峰映射
  configuration:
    map-underscore-to-camel-case: true

logging:
  level:
    com.djh: debug
    org.springframework: debug